apiVersion: batch/v1
kind: Job
metadata:
  name: test-worker-$PID
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: test-worker-$PID
    spec:
      containers:
        - name: worker
          image: gcr.io/jepsen-on-spanner-with-gke/jepsen-on-spanner
          command: ["java"]
          args: ["-jar","Jepsen-on-spanner.jar","--project","$PROJECT",
                 "--instance","$INSTANCE","--database","$DATABASE","--component","WORKER","--pID",
                 "$PID", "--config-file","test-config.json","--benchmark-type","$BENCHMARK"]
      restartPolicy: Never
